package jdbcPractice.lib.Accounts;

import java.sql.*; 

 

public class PatientDAO { 

 
private Connection connection; 

 

public PatientDAO() { 

try { 

 connection = DatabaseConnection.getConnection(); 
} catch (SQLException e) { 

 e.printStackTrace(); 

 } 

 } 

 public void createPatient(Patient patient) { 
String sql = "insert into patients(patientName,medicalHistory) values (?,?)"; 

	 

 try { 

PreparedStatement st = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS); 

st.setString(1, patient.getPatientName()); 

 st.setString(2, patient.getMedicalHistory()); 

 

 st.executeUpdate(); 

 

 ResultSet resultSet = st.getGeneratedKeys(); 

 

while (resultSet.next()) { 

 patient.setPatientID(resultSet.getInt(1)); 

 } 

 } catch (SQLException e) { 

 // TODO: handle exception 

 System.out.println(e.getMessage()); 
 } 

 // after succesfull insertion in database get autogenerated patientId and set that patientId to the patient object 

} 

 
 public Patient getPatientByID(int patientID) throws RecordNotFoundException { 
 // retrieve a patient record from database by patientID 

 String sql = "select * from patients where patientID = ?"; 

 Patient patient = null; 

 try { 

 PreparedStatement st = connection.prepareStatement(sql); 

 st.setInt(1, patientID); 

ResultSet resultSet = st.executeQuery(); 

 if(resultSet.next()){ 

 patient = new Patient(); 

 patient.setPatientID(resultSet.getInt(1)); 

 patient.setPatientName(resultSet.getString(2)); 

 patient.setMedicalHistory(resultSet.getString(3)); 

  

 } 

 else{ 

 throw new RecordNotFoundException("Patient with ID "+patientID+" not found"); 

 } 

 } catch (SQLException e) { 

// TODO: handle exception 
 e.getMessage(); 

} 

 return patient; 
 // throw RecordNotFoundException if patient with patientID not found 
 } 

 
public void close() { 

 // close database connection 

 try { 

connection.close(); 

} catch (Exception e) { 

 // TODO: handle exception 
 e.getMessage(); 

 } 

 } 

} 

 